name: Deploy Production
on: 
  push:
    branches: master
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Setup Node
        run: npm install
      - name: Run Tests
        run: echo Run Tests
      - name: Generate Production
        run: npm run generate
      - name: Deploy to Production
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: now --name collectionsapp --prod --token=${{ secrets.ZEIT_TOKEN }}
      